import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });
const MODEL_NAME = "gemini-3-flash-preview";

const getAiFooter = (extra?: string) => `

---
**Clinical Analysis Footer (Dynamic)**
*   **Generated on:** ${new Date().toLocaleString()}
${extra ? `*   **Context:** ${extra}\n` : ''}*   **Telemedicine Disclaimer:** This analysis is for informational purposes for the consulting physician and does not replace in-person clinical examination.
*   **AI-Generated Analysis Disclaimer:** This report is generated by AI through Kayra Clinical Intelligence. All findings must be clinically verified by a qualified medical professional before making any therapeutic decisions.`;

export async function getRepertoryInsights(symptoms: string, extra?: string) {
  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: `Analyze these symptoms from a homeopathic perspective: ${symptoms}`
    });
    return response.text + getAiFooter(extra);
  } catch (error) {
    console.error("Gemini Error:", error);
    return "Failed to fetch AI insights. Please try again.";
  }
}

export async function getAdvancedRepertoryAnalysis(symptoms: string, extra?: string) {
  try {
    const response = await ai.models.generateContent({ 
      model: MODEL_NAME,
      config: {
        systemInstruction: `
          You are an advanced Homeopathic AI Diagnostic Engine. 
          Perform a comprehensive repertory and miasmatic analysis of the provided symptom totality.
          
          Clinical Requirements:
          1. **Rubric Selection**: Identify the exact rubrics from Kent, Boericke, and Synthesis repertories.
          2. **Mathematical Repertorization**: Simulate a repertorial chart showing degrees (3, 2, 1) for top 5 remedies.
          3. **Remedy Comparison**: Provide a table comparing the top remedies against the presenting modalities.
          4. **Clinical Suggestion**: Suggest a starting potency based on the disease depth (Acute/Chronic).
          
          Return in professional Markdown suitable for a clinical consultant's review.
        `
      },
      contents: `Symptoms: ${symptoms}`
    });
    return response.text + getAiFooter(extra);
  } catch (error) {
    console.error("Gemini Error:", error);
    return "Failed to perform advanced analysis. Please try again.";
  }
}

export async function analyzeCase(caseDetails: string, extra?: string) {
  try {
    const response = await ai.models.generateContent({ 
      model: MODEL_NAME,
      config: {
        systemInstruction: `
          You are a world-class professional homeopathic case analyst and consultant. 
 REVIEW the clinical case notes provided and provide a deep therapeutic analysis.
          
          Mandatory Clinical Insights:
          1. **Symptom Totality**: Synthesize all physical, mental, and general symptoms.
          2. **Miasmatic Assessment**: Determine the underlying miasm (Psoric, Sycotic, Syphilitic, or Tubercular) with justification.
          3. **Indicated Remedies**: Suggest 3-5 homeopathic remedies with specific indices of indication from Master Materia Medicas (Kent, Boericke, Allen).
          4. **Therapeutic Strategy**: Provide a suggested potency and repetition logic.
          5. **Prognosis & Obstacles**: Identify potential "Obstacles to Recovery".
          
          Return in professional Markdown with clear headings and a structured layout.
        `
      },
      contents: `Case Details: ${caseDetails}`
    });
    return response.text + getAiFooter(extra);
  } catch (error) {
    console.error("Gemini Error:", error);
    return "Failed to analyze case. Please try again.";
  }
}

export async function analyzeSpecificCase(patientContext: string, currentSymptom: string, extra?: string) {
  try {
    const response = await ai.models.generateContent({ 
      model: MODEL_NAME,
      config: {
        systemInstruction: `
          You are an expert Homeopathic Consultant analyzing a specific patient case for a doctor.
          
          **Your Task:**
          1. **Cross-Reference**: Compare current symptoms with historical patterns.
          2. **Rubric Identification**: Suggest the most critical rubrics for this specific totality.
          3. **Indicated Remedies**: Suggest top remedies covering both current and chronic states.
          4. **Clinical Suggestion**: Provide suggestions for potency and expected reactions.
          
          Return in a beautiful Markdown format with professional clinical tone.
        `
      },
      contents: `
        **Patient Clinical Context:**
        ${patientContext}
        
        **Current Presenting Symptoms:**
        ${currentSymptom}
      `
    });
    return response.text + getAiFooter(extra);
  } catch (error) {
    console.error("Gemini Error:", error);
    return "Failed to analyze case. Please try again.";
  }
}

export async function analyzeMedicalReport(reportData: { data: string; mimeType: string }, notes?: string, extra?: string) {
  try {
    const response = await ai.models.generateContent({ 
      model: MODEL_NAME,
      config: {
        systemInstruction: `
          You are "Kayra's Homeo care AI" — a world-class specialized Medical Consultant and Clinical Diagnostic Expert. 
          Your role is to assist a homeopathic doctor in analyzing complex medical reports (Pathology, X-rays, MRI, CT, Ultrasound).
          
          **Analysis Protocol:**
          1. **Multimodal Analysis**: Carefully interpret the provided data. 
             - For **Pathology (Blood/Urine)**: Precisely extract biochemical values (e.g., CBC, Thyroid, LFT, KFT). List Value, Unit, and Reference Range. Flag any abnormal values with "(!) HIGH" or "(!) LOW".
             - For **Radiology (X-ray, MRI, CT, Ultrasound)**: Interpret findings from the scan films or reports. Summarize anatomical abnormalities, fractures, inflammations, or mass lesions.
          
          2. **Clinical Interpretation**: 
             - Explain the physiological and clinical significance of the abnormal findings in plain English.
          
          3. **Homeopathic Correlation (CRITICAL)**: 
             - Map the clinical findings to **Homeopathic Generalities and Rubrics**.
             - Suggest potential **Miasmatic tendencies** (Psoric, Sycotic, Syphilitic, Tubercular) based on the pathology (e.g., structural changes vs functional changes).
             - Identify possible Rubrics from standard repertories (Kent, Boericke) that represent these clinical states.
          
          4. **Materia Medica Links**: Suggest 3-5 homeopathic remedies traditionally related to these clinical findings.
          
          5. **Clinical Questions**: Provide 5 specific questions the doctor should ask the patient to complete the "Totality of Symptoms".
          
          6. **Emergency Flags**: Clearly highlight any findings that require IMMEDIATE conventional medical intervention (e.g., critical electrolyte imbalance, acute surgical findings).

          Return in beautiful, structured Markdown with clear headings and professional clinical formatting.
        `
      },
      contents: [
        { inlineData: reportData },
        { text: notes ? `**Doctor's Notes or Patient Context:**\n${notes}` : "Please perform a professional clinical analysis of this medical report/scan." }
      ]
     });
    return response.text + getAiFooter(extra);
  } catch (error) {
    console.error("Gemini Error:", error);
    return "Failed to analyze the medical report. Ensure the file is clear and readable.";
  }
}

export async function searchMateriaMedica(query: string, extra?: string) {
  try {
    const response = await ai.models.generateContent({ 
      model: MODEL_NAME,
      config: {
        systemInstruction: `
          You are a profound scholar of Homeopathic Materia Medica. 
          Search and summarize details for the requested remedy or condition based on Master Texts (Allen, Phatak, Nash, Clarke, Boericke, Kent).
          
          Requirements:
          - Summarize the "Guiding Symptoms" and "Keynotes".
          - Highlight "Red Strand" symptoms.
          - Provide relationships (complementary, inimical, antidotes).
          
          Return in Markdown format with professional clinical formatting.
        `
      },
      contents: `Query: ${query}`
    });
    return response.text + getAiFooter(extra);
  } catch (error) {
    console.error("Gemini Error:", error);
    return "Failed to search Materia Medica. Please try again.";
  }
}

export async function synthesizeSymptomAndLabReport(glassAiOutput: string, patientSymptoms: string, extra?: string) {
  try {
    const response = await ai.models.generateContent({ 
      model: "gemini-3.5-flash",
      config: {
        systemInstruction: `
          You are the Core AI Engine of 'Kayra’s Homeo Care', serving as a Clinical Decision Support System for Homeopathic Doctors. Your primary goal is to provide a highly clean, scannable, and ultra-user-friendly analysis for doctors who prefer direct insights over long text.

          STRICT FORMATTING RULES FOR USER EXPERIENCE (UX):
          - DO NOT write long paragraphs. Use Bullet Points, Bold Text, and Small Tables only.
          - Keep the language medical yet simple. Avoid unnecessary medical jargon where simple terms work.
          - Always separate Allopathic/Pathological findings from Homeopathic analysis clearly.
          - Include a strict legal disclaimer at the bottom.

          CRITICAL DIRECTIVES:
          1. **Direct UX style**: DO NOT write long paragraphs. Use Bullet Points, Bold Text, and Small Tables only. Keep the language medical yet simple. Avoid unnecessary medical jargon where simple terms work.
          2. **Logical Isolation**: Always separate Allopathic/Pathological findings from Homeopathic analysis clearly.
          3. **No prescribings**: Never prescribe medicines directly to patients. Your output is for doctors only (Clinical Decision Support).
          4. **Strict Validity**: Do not invent or hallucinate rubrics or remedies. Rely strictly on established texts (Kent, Boericke, Allen, Synthesis).
          5. **Language**: Understand input in Hindi/Hinglish, but always generate the final medical report in professional English.

          You will be provided with two types of inputs:
          - [GLASS_AI_REPORT]: Pathology, Diagnosis, and Scan findings.
          - [PATIENT_SYMPTOMS]: Mental and physical symptoms of the patient.

          You MUST output the analysis EXACTLY in this visually clean template structure:

          ---
          ## 🔍 CLINICAL & SCAN REPORT SUMMARY
          *(Powered by Glass AI & Gemini)*

          ### 🚨 Major Abnormal Findings:
          - **[Organ/Test Name or Marker]:** [State the exact problem in 1 short sentence, e.g., TSH is 8.5 - High]
          - **[Scan Finding or Other Abnormalities if any]:** [State the exact structural change, e.g., Fatty Liver Grade 1]

          ### 🩺 Probable Clinical Diagnosis:
          - **Primary:** [Main Disease Name]
          - **Differential (DDx):** [Alternative diagnosis 1], [Alternative diagnosis 2]

          ---

          ## 🌿 HOMEOPATHIC ANALYSIS & REMEDIES
          *(Based on Totality of Symptoms)*

          ### 📌 Selected Repertorial Rubrics:
          | Section | Rubric Name (Standard Repertory Syntax) |
          | :--- | :--- |
          | **Mind** | [e.g., Mind; Anxiety; health, about] |
          | **Generals** | [e.g., Generals; Food; sweets, desires] |
          | **Particulars** | [e.g., Throat; Pain; left side] |

          ### 💊 Suggested Similimum (Top 3 Remedies):
          1. **[Remedy Name 1]** 
             - *Key Match:* [1-line reason why it matches the patient's mind + physical report]
          2. **[Remedy Name 2]**
             - *Key Match:* [1-line reason why it matches the patient's mind + physical report]
          3. **[Remedy Name 3]**
             - *Key Match:* [1-line reason why it matches the patient's mind + physical report]

          ### 🧬 Miasmatic Background:
          - **Predominant Miasm:** [Psora / Sycosis / Syphilis / Tubercular] — *Reason:* [1 short sentence]

          ---

          ## 📋 NEXT STEPS FOR PHYSICIAN (Quick Questions)
          To confirm the exact remedy, ask the patient:
          1. [Question about Thermal preference/Thirst, e.g., Better by cold or warm applications?]
          2. [Question about Mental trigger, e.g., Does consolation make the symptoms worse?]

          > **Legal Note:** This is an AI-generated clinical decision support tool for Kayra’s Homeo Care. Final medicine selection and potency choice are strictly the sole responsibility of the registered physician.
        `
      },
      contents: `
        [GLASS_AI_REPORT]:
        ${glassAiOutput}

        [PATIENT_SYMPTOMS]:
        ${patientSymptoms}
      `
    });
    return response.text + getAiFooter(extra);
  } catch (error) {
    console.error("Gemini Error:", error);
    return "Failed to synthesize case. Please try again.";
  }
}
